### ISSUE TITLE
add Cargo.lock to repository

### ISSUE THREAD

**Issue by DarkKronicle** [idanarye/nu_plugin_skim#10]
Hello! I've been really enjoying this plugin and am interested in packaging it for Nix. Nix requires locked dependencies for all of it's packages, so I was wondering if you would be open to commiting the `Cargo.lock` file. I can manually add one to the nixpkgs repository, but there seems to be an ongoing effort to reduce manually added `Cargo.lock`'s.

(The comment here recommends commit it https://github.com/idanarye/nu_plugin_skim/blob/9d2f57b40f7a8e7afa005f35c35c3df3700746d6/.gitignore#L6)

Rust has also recently changed their stance on `Cargo.lock` for certain projects, which is to now commit unless you have specific reasons against it. 

- https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html
- https://doc.rust-lang.org/1.79.0/cargo/faq.html#why-have-cargolock-in-version-control

**Comment by idanarye** [comment]
Do I need to make a release, or will you be building from a commit?

**Comment by DarkKronicle** [comment]
Thanks for the quick response! 

A minor release would be preferable if it's not too much work.

**Comment by idanarye** [comment]
Done
