### ISSUE TITLE
slowish `sk -f {get COLUMN}`

### ISSUE THREAD

**Issue by dj8yfo** [idanarye/nu_plugin_skim#18]
Using it. It's quite nice. Though it's quite sluggish on large file sets. It's noticeable compared to vanilla `sk` binary.
I did another tool another day, based on `skim` library, and had a similar problem. 
I sincerely do not remember, how i solved it. It had to do something with not blocking  on user input
and let suggestions fly in the background. (this other tool does a lot of processing per item, so resetting
the search is visibly filled in with all suggestions during a few secs. But it doesn't block and user can start filtering the search
while new and new suggestions finish processing)

Hope this helps improve `nu_plugin_skim`.

**Comment by dj8yfo** [comment]
Ok , more precisely, `ls **/* | sk` is fast. 
`ls -a **/* | get name | sk` is fast. 

but `ls **/* | sk -f {get name}` is slow

**Comment by idanarye** [comment]
Since ̀-f̀ is the issue, I may be able to fix it by caching or pre-calculating the formatting lambda.

**Comment by idanarye** [comment]
@dj8yfo - please check the `fix/18-slow-format-flag` branch and see if it fixes the sluggishness. I was unable to replicate it locally so I can't tell.

**Comment by dj8yfo** [comment]
@idanarye i had to update nu 0.97.1 -> 0.100.0 and nu_skim_plugin 0.5.0 -> 0.9.0

can confirm that the branch fixes the perceived issue for me, as on a 70k files dir it was lagging when trying to input new chars into skim search string (on 0.9.0), 
on 0.9.0 branch it does not
