### ISSUE TITLE
Support interactive mode

### ISSUE THREAD

**Issue by idanarye** [idanarye/nu_plugin_skim#4]
For this, I need this to get merged: https://github.com/kimono-koans/two_percent/pull/12

Once it's in and they make a release, I can migrate to [the "two_percent" fork of skim](https://crates.io/crates/two_percent) and support this kind of syntax:

```nushell
sk -i --cmd {rg -l $in} --preview {rg $cq $in}
```

I need to figure out though how to get `$cq` (and other parameters - like `$q`) inside the closure. I don't want to use positional because I can't do introspection and it may mess up the way I use `$in`...

**Comment by fujibearly** [comment]
Hi,  I realize it is a year later, wondering if any progress was made on this. I know that neither {} nor $in can be passed to the -c closure, or at least I have not figured out the proper syntax. Any updates? Thank you
